### ISSUE TITLE
Possible next steps

### ISSUE THREAD

**Issue by matheusgs-ciandt** [gvicentin/slacks#1]
Here are a list of some possible next steps

 - Better list option showing the presets as tables, with the text and duration

 - New command to `create`
 `slacks new status "status name"  "icon" "duration"`
  
 - New command to `update` 
 `slacks update status "status name" "icon" "duration"`
  
 - New command to`delete` 
`slacks delete status "status name"` 
  
 - Set the profile as active or away for multiple workplaces
`slacks set profile active |  slacks set profile away`

**Comment by matheusgs-ciandt** [comment]
Adding:

- Turn notification on and off for a period of time
`slacks pause notifications 60 | slacks resume notifications`

**Comment by gvicentin** [comment]
Thanks for sharing the ideas. I'm going to address some of them in the next release.

> Better list option showing the presets as tables, with the text and duration

Definitely need to have for the next version.

 > New command to update

Yes! I'm thinking to have `set` and `preset`, where the first will receive the arguments like you said and the second uses the `PRESET_NAME`  (which is the current `set` in the v0.1.0) 

**About the notifications.**
Definitely is something missing. I was thinking that we could add as an preset variable, such as `PRESET_xxx_PAUSE_NOTIFICATION=true`. That way you can configure custom status and also don't receive notification while they are active if you wish.

**Comment by gvicentin** [comment]
Resolved in the new release [v0.2.0](https://github.com/gvicentin/slacks/releases/tag/v0.2.0)
